databases:
  - name: tourney-db
    databaseName: tournament_db
    user: tournament_user

services:
  - type: web
    name: tournament-project
    env: python
    repo: https://github.com/irshadmuhammed/kaalapani_efootball
    branch: main
    buildCommand: ./build.sh
    startCommand: gunicorn tournament_project.wsgi --log-file -
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: 'false'
      - key: DJANGO_SETTINGS_MODULE
        value: tournament_project.settings
      - key: ALLOWED_HOSTS
        value: '*'
      - key: DATABASE_URL
        fromDatabase:
          name: tourney-db
          property: connectionString
